export const albumDummyData = [
  {
    id: 1,
    cover: '/vache.jpg',
    album: 'Album Name',
    artistName: 'zviadi',
    songCount: 50,
  },
  {
    id: 2,
    cover: '/vache.jpg',
    album: 'Album Name',
    artistName: 'zviadi',
    songCount: 30,
  },
  {
    id: 3,
    cover: '/vache.jpg',
    album: 'Album Name',
    artistName: 'zviadi',
    songCount: 70,
  },
  {
    id: 4,
    cover: '/vache.jpg',
    album: 'Album Name',
    artistName: 'zviadi',
    songCount: 20,
  },
  {
    id: 5,
    cover: '/vache.jpg',
    album: 'Album Name',
    artistName: 'zviadi',
    songCount: 60,
  },
  {
    id: 6,
    cover: '/vache.jpg',
    album: 'Album Name',
    artistName: 'zviadi',
    songCount: 40,
  },
  {
    id: 7,
    cover: '/vache.jpg',
    album: 'Album Name',
    artistName: 'zviadi',
    songCount: 80,
  },
  {
    id: 8,
    cover: '/vache.jpg',
    album: 'Album Name',
    artistName: 'zviadi',
    songCount: 90,
  },
];
