export const songData = [
  {
    id: 1,
    cover: '/vache.jpg',
    music: 'zddzddzdd',
    album: 'asdsadsad',
    artistName: 'asdsadds',
    duration: '00:32',
  },
  {
    id: 2,
    cover: '/vache.jpg',
    music: 'zddzddzdd',
    album: 'asdsadsad',
    artistName: 'asdsadds',
    duration: '00:32',
  },
  {
    id: 3,
    cover: '/vache.jpg',
    music: 'zddzddzdd',
    album: 'asdsadsad',
    artistName: 'asdsadds',
    duration: '00:32',
  },
  {
    id: 4,
    cover: '/vache.jpg',
    music: 'zddzddzdd',
    album: 'asdsadsad',
    artistName: 'asdsadds',
    duration: '00:32',
  },
  {
    id: 5,
    cover: '/vache.jpg',
    music: 'zddzddzdd',
    album: 'asdsadsad',
    artistName: 'asdsadds',
    duration: '00:32',
  },
  {
    id: 6,
    cover: '/vache.jpg',
    music: 'zddzddzdd',
    album: 'asdsadsad',
    artistName: 'asdsadds',
    duration: '00:32',
  },
  {
    id: 7,
    cover: '/vache.jpg',
    music: 'zddzddzdd',
    album: 'asdsadsad',
    artistName: 'asdsadds',
    duration: '00:32',
  },
  {
    id: 8,
    cover: '/vache.jpg',
    music: 'zddzddzdd',
    album: 'asdsadsad',
    artistName: 'asdsadds',
    duration: '00:32',
  },
  {
    id: 9,
    cover: '/vache.jpg',
    music: 'zddzddzdd',
    album: 'asdsadsad',
    artistName: 'asdsadds',
    duration: '00:32',
  },
  {
    id: 10,
    cover: '/vache.jpg',
    music: 'zddzddzdd',
    album: 'asdsadsad',
    artistName: 'asdsadds',
    duration: '00:32',
  },
];
